# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swahn-Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  # Pods for Swahn-Projec
  pod 'SwiftyJSON'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'Swahn-ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swahn-ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
